name: Documentation

on:
  push:
    branches: [ main, master, development, release] 

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Полная история для деплоя
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install Sphinx
      run: pip install sphinx
    
    - name: Generate documentation
      run: |
        # Создаем структуру в корневой директории
        sphinx-quickstart --project "Project" --author "Author" --release "1.0" -q --no-sep
        
        # Добавляем настройки
        echo "
        import sys
        import os
        sys.path.insert(0, os.path.abspath('.'))
        extensions = ['sphinx.ext.autodoc']
        " >> conf.py
        
        # Создаем простой index.rst
        echo "Documentation
        =============
        
        Hello World" > index.rst
        
        # Собираем документацию
        sphinx-build -b html . _build/html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # используем secrets.GITHUB_TOKEN
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
        # Папка с собранной документацией
        publish_dir: ./_build/html
        
        # настройки:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy docs: ${{ github.sha }}'
        
        # Целевая ветка (gh-pages)
        publish_branch: gh-pages
